# Site Settings
baseurl: "maulanaanab"
url : "https://seelenbrecher.github.io/"

# Blog Settings
theme_settings :
  title : Anab Maulana Barik
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/anab.png
    username : Anab Maulana Barik
    description : Anab is a PhD candidate in Computer Science, National University of Singapore. His research focus in Natural Language Processing, specifically in Automated Claim Verification.
    email: anabmaulana [at] u.nus.edu
        
  # Icons
  icons :
    email:  maulanaanab@gmail.com
    google_scholar: https://scholar.google.com/citations?user=bSW0QS0AAAAJ&hl=en
    linkedin:  https://www.linkedin.com/in/anabmaulana/
    github: seelenbrecher
    scholar: kh77qB4AAAAJ
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
